<?php
require_once __DIR__ . '/saas/bootstrap.php';
$user = require_auth(); $db = control_db(); $tenant = current_tenant();
if (!$tenant) { http_response_code(404); exit('Loja não encontrada.'); }
$message = null; $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $hostname = strtolower(trim((string)($_POST['hostname'] ?? ''))); $hostname = preg_replace('/^https?:\/\//', '', $hostname); $hostname = trim($hostname, " /\t\n\r\0\x0B");
    if (!preg_match('/^(?=.{4,255}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/', $hostname)) $error = 'Informe um domínio válido, como www.minhaloja.com.br.';
    else { $token = bin2hex(random_bytes(20)); $type = 'custom'; $status = 'pending'; $stmt = $db->prepare('INSERT INTO domains (tenant_id,hostname,type,status,verification_token) VALUES (?,?,?,?,?)'); $stmt->bind_param('issss', $tenant['id'], $hostname, $type, $status, $token); if ($stmt->execute()) $message = 'Domínio adicionado. Configure o DNS e use o botão Verificar.'; else $error = 'Esse domínio já está cadastrado ou não está disponível.'; }
}
$stmt = $db->prepare('SELECT * FROM domains WHERE tenant_id=? ORDER BY id'); $stmt->bind_param('i', $tenant['id']); $stmt->execute(); $domains = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
page_start('Painel'); ?><div class="nav"><strong>Criador de Sites</strong><a class="button ghost" href="/logout.php">Sair</a></div><div class="card"><span class="eyebrow">PAINEL DA LOJA</span><h1><?= e($tenant['name']) ?></h1><p class="muted">Conta: <?= e($user['email']) ?> · Banco isolado: ativo</p><?php if ($message): ?><div class="notice"><?= e($message) ?></div><?php endif; ?><?php if ($error): ?><div class="notice error"><?= e($error) ?></div><?php endif; ?><div class="grid"><div class="card"><div class="stat">1</div><div class="muted">Loja independente</div></div><div class="card"><div class="stat"><?= count($domains) ?></div><div class="muted">Domínios configurados</div></div><div class="card"><div class="stat">Ativo</div><div class="muted">Provisionamento</div></div></div><h2>Domínios</h2><table class="table"><thead><tr><th>Endereço</th><th>Tipo</th><th>Status</th><th>Ação</th></tr></thead><tbody><?php foreach ($domains as $domain): ?><tr><td><?= e($domain['hostname']) ?></td><td><?= e($domain['type']) ?></td><td><?= e($domain['status']) ?></td><td><?php if ($domain['type'] === 'custom' && $domain['status'] !== 'active'): ?><a href="/verify-domain.php?id=<?= (int)$domain['id'] ?>">Verificar</a><?php else: ?><a href="http://<?= e($domain['hostname']) ?>" target="_blank">Abrir</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><h2>Adicionar domínio próprio</h2><p class="muted">Aponte um registro <strong>CNAME</strong> para <strong><?= e((string)envv('RAILWAY_PUBLIC_DOMAIN', 'seu-servico.up.railway.app')) ?></strong>.</p><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label class="field">Domínio<input name="hostname" placeholder="www.minhaloja.com.br" required></label><button class="button" type="submit">Adicionar domínio</button></form><h2>Gerenciar conteúdo</h2><p><a class="button" href="http://<?= e($domains[0]['hostname'] ?? '') ?>/@SERVIDOR/config.php">Abrir painel legado</a> <a class="button ghost" href="http://<?= e($domains[0]['hostname'] ?? '') ?>" target="_blank">Ver loja publicada</a></p></div><?php page_end(); ?>
